# Generated by Django 4.2.1 on 2023-10-11 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='publishing_date',
        ),
        migrations.AddField(
            model_name='library',
            name='is_published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
